using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApi.Services.EmlakAz
{
    public class EmlakAzMarksNames
    {
        Dictionary<string, int> marksNames = new Dictionary<string, int>();

        public EmlakAzMarksNames()
        {
            marksNames.Add("Axundov bağı",2);
            marksNames.Add("Ayna Sultanova heykəli",7);
            marksNames.Add("Azadlıq meydanı",8);
            marksNames.Add("Azneft meydanı",12);
            marksNames.Add("Azərbaycan Dillər Universiteti",9);
            marksNames.Add("Azərbaycan kinoteatrı",10);
            marksNames.Add("Azərbaycan Тurizm İnstitutu",11);
            marksNames.Add("Bakı Asiya Universiteti",13);
            marksNames.Add("Bakı Dövlət Universiteti",14);
            marksNames.Add("Bakı Musiqi Akademiyası",15);
            marksNames.Add("Bakı Slavyan Universiteti",16);
            marksNames.Add("Bayıl parkı",17);
            marksNames.Add("Beşmərtəbə",18);
            marksNames.Add("Botanika bağı",19);
            marksNames.Add("Cavanşir körpüsü",20);
            marksNames.Add("Dağüstü parkı",21);
            marksNames.Add("Dostluq kinoteatrı",22);
            marksNames.Add("Dövlət Statistika Komitəsi",24);
            marksNames.Add("Dövlət İdarəçilik Akademiyası",23);
            marksNames.Add("Fontanlar bağı",25);
            marksNames.Add("Hüseyn Cavid parkı",26);
            marksNames.Add("Keşlə bazarı",33);
            marksNames.Add("Koala parkı",34);
            marksNames.Add("M.Hüseynzadə parkı",38);
            marksNames.Add("M.Ə.Sabir parkı",37);
            marksNames.Add("Molokan bağı",39);
            marksNames.Add("Milli Konservatoriya",42);
            marksNames.Add("Mərkəzi Univermaq",41);
            marksNames.Add("Neapol dairəsi",44);
            marksNames.Add("Neft Akademiyası",45);
            marksNames.Add("Neftçi bazası",46);
            marksNames.Add("Nizami kinoteatrı",50);
            marksNames.Add("Nəriman Nərimanov parkı",47);
            marksNames.Add("Nərimanov heykəli",48);
            marksNames.Add("Nəsimi bazarı",49);
            marksNames.Add("Park Zorge",51);
            marksNames.Add("Pedaqoji Universiteti",52);
            marksNames.Add("Prezident parkı",54);
            marksNames.Add("Qubernator parkı",36);
            marksNames.Add("Qış parkı",35);
            marksNames.Add("Respublika stadionu",55);
            marksNames.Add("Rusiya səfirliyi",57);
            marksNames.Add("Rəssamlıq Akademiyası",56);
            marksNames.Add("Sahil bağı",58);
            marksNames.Add("Sevil Qazıyeva parkı",60);
            marksNames.Add("Sirk",62);
            marksNames.Add("Sovetski",63);
            marksNames.Add("Space TV",64);
            marksNames.Add("Səməd Vurğun parkı",61);
            //marksNames.Add("Altes Plaza",);
            marksNames.Add("Texniki Universiteti",69);
            marksNames.Add("Tibb Universiteti",71);
            marksNames.Add("Təhsil Nazirliyi",70);
            marksNames.Add("Ukrayna dairəsi",73);
            //marksNames.Add("Xalça Muzeyi",);
            marksNames.Add("Yasamal bazarı",74);
            marksNames.Add("Zabitlər parkı",75);
            marksNames.Add("Zoopark",77);
            marksNames.Add("Zərifə Əliyeva adına park",76);
            //marksNames.Add("Sərhədçi İdman kompleksi",);
            marksNames.Add("İncəsənət və Mədəniyyət Un.",31);
            //marksNames.Add("İnşaat Universiteti",);
            marksNames.Add("İqtisadiyyat Universiteti",30);
            marksNames.Add("İzmir parkı",32);
            marksNames.Add("İçəri Şəhər",28);
            marksNames.Add("Şəfa stadionu",65);
            marksNames.Add("Şəhidlər xiyabanı",66);
            marksNames.Add("Şəlalə parkı",67);
            marksNames.Add("Şərq Bazarı",68);
            //marksNames.Add("Qələbə dairəsi",);
            //marksNames.Add("Sevinc k/t",);
            //marksNames.Add("Hərbi Hospital",);
            //marksNames.Add("Yasamal parkı",);
            //marksNames.Add("Təzə bazar",);
            //marksNames.Add("Yaşıl bazar",);
            //marksNames.Add("AF Business House",);
            //marksNames.Add("AGA Business Center",);
            //marksNames.Add("Babək Plaza",);
            //marksNames.Add("Bridge Plaza",);
            //marksNames.Add("Caspian Plaza",);
            //marksNames.Add("Çıraq Plaza",);
            //marksNames.Add("Crystal Plaza",);
            //marksNames.Add("Dalğa Plaza",);
            //marksNames.Add("Dəmirçi Plaza",);
            //marksNames.Add("Hyatt Regency",);
            //marksNames.Add("ISR Plaza",);
            //marksNames.Add("Landmark",);
            marksNames.Add("Port Baku",53);
            //marksNames.Add("World Business Center",);
            //marksNames.Add("A.S.Puşkin parkı",);
            //marksNames.Add("C.Cabbarlı heykəli",);
            //marksNames.Add("Heydər Əliyev sarayı",);
            //marksNames.Add("Nəsimi heykəli",);
            //marksNames.Add("Araz kinoteatrı",);
            //marksNames.Add("Vətən kinoteatrı",);
            //marksNames.Add("Absheron Marriott otel",);
            //marksNames.Add("Ambassador otel",);
            //marksNames.Add("Avropa otel",);
            //marksNames.Add("Fairmont otel",);
            //marksNames.Add("Four Seasons otel",);
            //marksNames.Add("Hilton otel",);
            //marksNames.Add("Park Inn",);
            //marksNames.Add("Qafqaz Resort otel",);
            //marksNames.Add("Daxili İşlər Nazirliyi",);
            //marksNames.Add("Ədliyyə Nazirliyi",);
            //marksNames.Add("Ekologiya və Təbii Sərvətlər Nazirliyi",);
            //marksNames.Add("Əmək və Əhalinin Sosial Müdafiəsi Nazirliyi",);
            //marksNames.Add("Energetika Nazirliyi",);
            //marksNames.Add("Fövqəladə Hallar Nazirliyi",);
            //marksNames.Add("Gənclər və İdman Nazirliyi",);
            //marksNames.Add("İqtisadi İnkişaf Nazirliyi",);
            //marksNames.Add("Maliyyə Nazirliyi",);
            //marksNames.Add("Milli Təhlükəsizlik Nazirliyi",);
            //marksNames.Add("Müdafiə Sənayesi Nazirliyi",);
            //marksNames.Add("Nəqliyyat Nazirliyi",);
            //marksNames.Add("Rabitə və Yüksək Texnologiyalar Nazirliyi",);
            //marksNames.Add("Səhiyyə Nazirliyi",);
            //marksNames.Add("Vergilər Nazirliyi",);
            //marksNames.Add("Xarici İşlər Nazirliyi",);
            //marksNames.Add("Dədə Qorqud parkı",);
            //marksNames.Add("Dənizkənarı Milli park",);
            //marksNames.Add("Fəvvarələr meydanı",);
            //marksNames.Add("Flame Towers",);
            //marksNames.Add("Tarqovu",);
            //marksNames.Add("Montin adına park",);
            //marksNames.Add("Musabəyov parkı",);
            //marksNames.Add("ABŞ səfirliyi",);
            //marksNames.Add("Türkiyə səfirliyi",);
            //marksNames.Add("Olimpia Stadionu",);
            //marksNames.Add("Tofiq Bəhramov stadionu",);
            //marksNames.Add("ANS telekanalı",);
            //marksNames.Add("ATV telekanalı",);
            //marksNames.Add("AZTV telekanalı",);
            //marksNames.Add("İctimai telekanalı",);
            //marksNames.Add("Lider telekanalı",);
            //marksNames.Add("28 Mall",);
            //marksNames.Add("AMAY",);
            //marksNames.Add("Aygun City",);
            //marksNames.Add("Bakı univermağı",);
            //marksNames.Add("Binə ticarət mərkəzi",);
            //marksNames.Add("Caspian Shopping Center",);
            //marksNames.Add("Elit ticarət mərkəzi",);
            //marksNames.Add("Metropark",);
            //marksNames.Add("Moskva univermağı",);
            //marksNames.Add("MUM",);
            //marksNames.Add("Nargiz ticarət mərkəzi",);
            //marksNames.Add("Park Bulvar",);
            //marksNames.Add("Sədərək ticarət mərkəzi",);
            //marksNames.Add("Şüvəlan Park ticarət mərkəzi",);
            //marksNames.Add("Xəqani ticarət mərkəzi",);
            //marksNames.Add("ADA universiteti",);
            //marksNames.Add("Aviasiya Akademiyası Universiteti",);
            //marksNames.Add("Kooperasiya Universiteti",);
            //marksNames.Add("Memarlıq və İnşaat Universiteti",);
            //marksNames.Add("Odlar Yurdu Universiteti",);
            //marksNames.Add("Qafqaz Universiteti",);
            //marksNames.Add("Qərb Universiteti",);
            //marksNames.Add("Təfəkkür Universiteti",);
            //marksNames.Add("Xəzər Universiteti",);
            //marksNames.Add("Heydər Əliyev Mərkəzi",);
            //marksNames.Add("Fövqəladə Hallar Nazirliyi Akademiyası",);
            //marksNames.Add("Abu Arena",);
            //marksNames.Add("Milli Məclis",);
            //marksNames.Add("Olimpik Star",);
            //marksNames.Add("Qız Qalası",);
            //marksNames.Add("Koroğlu Parkı",);
            //marksNames.Add("Park Azure",);
            //marksNames.Add("Megafun",);
            //marksNames.Add("Özbəkistan səfirliyi",);
            //marksNames.Add("İran İslam Respublikası səfirliyi",);
            //marksNames.Add("Asan Xidmət-1",);
            //marksNames.Add("Asan Xidmət-2",);
            //marksNames.Add("Asan Xidmət-3",);
            //marksNames.Add("Asan Xidmət-4",);
            //marksNames.Add("Asan Xidmət-5",);
            //marksNames.Add("Mərkəzi Neftçilər xəstxəxanası",);
            //marksNames.Add("Çin səfirliyi",);
            //marksNames.Add("Aqua Park",);
            //marksNames.Add("AAF PARK",);
            //marksNames.Add("Qurtuluş - 93 Yaşayış Kompleksi",);
            //marksNames.Add("Heydər Məscidi",);
            //marksNames.Add("Atatürk parkı",);
            //marksNames.Add("Baku Mall",);
            //marksNames.Add("Sevgi parkı",);
            //marksNames.Add("C.Naxçıvanski adına Hərbi Akademiya",);
        }

        public Dictionary<string, int> GetMarksNamesAll()
        {
            return marksNames;
        }
    }
}
